version: "3"

dotenv: 
  - .env

vars:
  TITLE: Loan Origination
  DEFAULT_REGION: eastus2
  APP_PORT: 8081

includes:
  workflow: 
    taskfile: ./Taskfile.workflow.yaml
    internal: false

  classic: 
    taskfile: ./Taskfile.classic.yaml
    internal: false
  
tasks:
  default:
    cmds:
      - task --list

  up:
    desc: Creates complete Azure environment for {{.TITLE}}
    cmds:
      - task: init
      - task: apply
  
  init:
    desc: Initializes Terraform for {{.TITLE}}
    cmds:
      - terraform -chdir=./infrastructure workspace new {{.REGION}} || true
      - terraform -chdir=./infrastructure workspace select {{.REGION}}
      - terraform -chdir=./infrastructure init
    vars:
      REGION: "{{default .DEFAULT_REGION .CLI_ARGS}}"

  apply:
    desc: Applies Terraform infrastructure for {{.TITLE}}
    cmds:
      - terraform -chdir=./infrastructure apply -auto-approve -compact-warnings
        -var "region={{.REGION}}"
        -var "tags={{.TITLE}}"
    vars:
      REGION: "{{default .DEFAULT_REGION .CLI_ARGS}}"

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
      - powershell -NoProfile -Command "az group list --tag Application='{{.TITLE}}' --query '[].name' -o tsv | % { az group delete --verbose -y --no-wait --name $_ }"
      - powershell -NoProfile -Command "Set-Location infrastructure; Remove-Item -Recurse -Force terraform.tfstate.d, .terraform.lock.hcl, .terraform, terraform.tfstate, terraform.tfstate.backup, .terraform.tfstate.lock.info -ErrorAction SilentlyContinue"